build::puller:
  image: golang:1.19.1
  stage: build
  before_script:
    - curl https://get.please.build | bash
  script:
    - ./pleasew build --arch=linux_amd64 tools
    - ./pleasew build --arch=darwin_amd64 tools
    - ./pleasew build --arch=darwin_arm64 tools
    - mkdir -p dist
    - cp $(./pleasew query outputs --arch=linux_amd64 tools) dist/ 
    - cp $(./pleasew query outputs --arch=darwin_amd64 tools) dist/
    - cp $(./pleasew query outputs --arch=darwin_arm64 tools) dist/
  artifacts:
    paths:
      - dist
    expire_in: 24 hours


deploy:
  stage: deploy
  image: ubuntu:20.04
  dependencies:
      - build::puller
  only:
      - tags
  before_script:
    - apt update && apt install -y curl bzip2
    - curl -Lo - https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_amd64.tar.gz | tar zxf -
    - mv ghr_v0.13.0_linux_amd64/ghr . && rm -rf ghr_v0.13.0_linux_amd64
  script:
    - mv plz-out/gen/tools/tools.tar.gz tools-${CI_COMMIT_TAG}.tar.gz 
    - ./ghr -t ${GITHUB_TOKEN} -u tcncloud -r please.containers -c ${CI_COMMIT_SHA} -replace  ${CI_COMMIT_TAG} tools-${CI_COMMIT_TAG}.tar.gz
