build::puller:
  image: golang:latest 
  stage: build
  script:
    - w=$(pwd)
    - go get github.com/mitchellh/gox
    - go get -v -t  github.com/bazelbuild/rules_docker/container/go/cmd/puller
    - cd $GOPATH/src/github.com/bazelbuild/rules_docker/
    - git checkout v0.15.0
    - cd container/go/cmd
    - for i in $(ls); do  cd $i; gox -arch="amd64" -os="linux darwin" ./... ;  cd ../; done
    - tar zcf rules_docker_darwin_amd64.tar.gz $(find . -type f -name "*_darwin_amd64")
    - tar zcf rules_docker_linux_amd64.tar.gz $(find . -type f -name "*_linux_amd64")
    - mv *.tar.bz2 $w
    - cd $w
  artifacts:
    paths:
      - /*.tar.gz
