build::puller:
  image: golang:latest 
  stage: build
  script:
    - go get github.com/mitchellh/gox
    - go get -d github.com/bazelbuild/rules_docker/container/go/cmd/puller
    - gox -arch="amd64" -os="linux darwin" github.com/bazelbuild/rules_docker/container/go/cmd/puller
    - ls -la 
